image: node:14

pipelines:
  pull-requests:
    '**':
      - step:
          name: Install Yarn and Linting
          caches:
            - node
          script:
            - apt-get update && apt-get install -y curl
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
            - apt-get update && apt-get install -y yarn
            - export TERM=xterm
            - yarn install
            - yarn ts:check
            - yarn lint:check
            - yarn format:check
