image: node:14.16.0

pipelines:
  default:
    - step:
        name: Build and deploy to EC2
        script:
          - apt-get update
          - apt-get install -y sshpass
          # - npm install --force
          # - npm run build
          - ssh -v -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd -p /var/www/alsodev_frontend/'
          - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r build/* $SSH_USER@$SSH_HOST:/var/www/alsodev_frontend/
