declare module 'heroicons';
// declare module '@dnd-kit/sortable';
declare module 'react-timecode';
declare module 'ntc-ts';
declare module 'react-timer-wrapper';
declare module 'react-color';
declare module 'cypress';
declare module '@ckeditor/ckeditor5-react';
declare module '@ckeditor/ckeditor5-build-classic';
declare module 'react-color/lib/components/common';
